#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_SW_CODEC_OPUS=y
# Suppress warnings introduced by the Opus encoder source tree
CONFIG_COMPILER_OPT="-Wno-double-promotion -Wno-maybe-uninitialized -Wno-unused-variable -Wno-stringop-overflow"
